### ISSUE TITLE
Неинформативные названия для переменных button1 и 2

### ISSUE THREAD

**Issue by generalova-kate** [nn-students-2020h1/fantastic-6-team#3]
https://github.com/nn-students-2020h1/fantastic-6-team/blob/fdc19219751c63897fa6961f2c8e5409e076b21d/fantastic_chat_bot.py#L134

**Comment by generalova-kate** [comment]
Бага весит уже 20 дней, как прогресс?

**Comment by DmitryKizaev** [comment]
Исправлено вместе с остальными багами, пулл реквест ожидает
